title: Joshua Owoyemi
description: PhD, Consultant and Data Scientist.
show_downloads: false
theme: jekyll-theme-slate

disqus:
  shortname: https-toluwajosh-github-io-1
  url: https://toluwajosh.github.io/

# Analytics and webmaster tools stuff goes here
google_analytics: UA-93933771-1
# google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: C0CB371ACFA5EFD6FB47169BFFBA8217

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# collections:
#   authors:
